### ISSUE TITLE
Missing DBC files

### ISSUE THREAD

**Issue by ekampourakis** [floGik/RaceControl#1]
I've been trying to run your RaceControl application.

I setup `nginx` and did a couple of modifications regarding the `canmatrix` version (that I ended up using from your profile as well) and some minor adaptations on the paths but still can't get it to run.

The `racecan.py` executable throws an error regarding `.dbc` files not existing. `blacklist, priority, guiupper, guilower, guitext`
I've bypassed that error by creating empty `.dbc` files hoping it will just use the empty `CanMatrix` type but the `guiupper, guilower, guitext` files seem to be required. 

I've read the documentation carefully but couldn't find an explanation regarding those 3 files or any template on how to make it work. Could you please attach some template files or add a brief explanation on what those file are supposed to contain as to make the application start.

Best regards,
Manos

**Comment by cdbrkfxrpt** [comment]
Hi Manos,

from your profile pic I assume you're working in Formula Student. Cool! I also hope you're not relying on this tiny little application for anything there, it's not really fit for that :) ... this is the code for my Bachelor's project and since I didn't really care much for the front end it isn't anything particular to look at. The backend _does work_ but isn't very reliable either. In fact, this ended up never being used in any of our cars for those reasons.

Regarding your questions: yes, those three are required. However all that part is pretty broken and works only in the original setup. If you want to use this, your best served modifying the code for this directly. I'll try to explain what all this does:

```python
        try:
            # blacklist and priority are required but can be empty
            blacklistdbc = im.importany(dbcpath + '/blacklist.dbc')['']
            prioritydbc = im.importany(dbcpath + '/priority.dbc')['']
            # the GUI has three fields: an upper graph, a lower graph and a text field. the code
            # here loads DBC files which hold information as to which graph component shall
            # show which parts of the CAN stream. it's probably best to comment all this out
            # for now and try to get it working manually.
            guiupperdbc = im.importany(dbcpath + '/guiupper.dbc')['']
            guilowerdbc = im.importany(dbcpath + '/guilower.dbc')['']
            guitextdbc = im.importany(dbcpath + '/guitext.dbc')['']
        except FileNotFoundError:
            pass

        blacklist = [frame._Id for frame in blacklistdbc._fl._list]
        priority = [frame._Id for frame in prioritydbc._fl._list]

        msgfilter = {}

        # the mentioned graphs receive all their data from one CAN message each. this
        # message contains all channels for each respective view. probably best to comment
        # this out as well, and manually define the ID(s) you want to send to each graph view.
        upperid = guiupperdbc._fl._list[0]._Id
        lowerid = guilowerdbc._fl._list[0]._Id
        textid = guitextdbc._fl._list[0]._Id

        # what we want to end up with are dicts in which the first level tells us which CAN ID
        # we're looking for, on the second level we want to end up with which channel is
        # offset how far into the payload, and on the last level we want to end up start, size
        # and name of the channel. endianness is ommitted because big endian / Motorola
        # is simply assumed.
        #
        # here we start with the first level...
        msgfilter[upperid] = {}
        msgfilter[lowerid] = {}
        msgfilter[textid] = {}

        offset = 0

        # ... moving on to the second...
        uppersignals = guiupperdbc._fl._list[0]._signals
        for sig in uppersignals:
            # ... and finally the third and last.
            msgfilter[upperid][offset] = {}
            msgfilter[upperid][offset]['start'] = int(sig._startbit / 8)
            msgfilter[upperid][offset]['size'] = int(sig._signalsize / 8)
            msgfilter[upperid][offset]['name'] = sig._name
            offset += 1

        # ... moving on to the second...
        lowersignals = guilowerdbc._fl._list[0]._signals
        for sig in lowersignals:
            # ... and finally the third and last.
            msgfilter[lowerid][offset] = {}
            msgfilter[lowerid][offset]['start'] = int(sig._startbit / 8)
            msgfilter[lowerid][offset]['size'] = int(sig._signalsize / 8)
            msgfilter[lowerid][offset]['name'] = sig._name
            offset += 1

        # ... moving on to the second...
        textsignals = guitextdbc._fl._list[0]._signals
        for sig in textsignals:
            # ... and finally the third and last.
            msgfilter[textid][offset] = {}
            msgfilter[textid][offset]['start'] = int(sig._startbit / 8)
            msgfilter[textid][offset]['size'] = int(sig._signalsize / 8)
            msgfilter[textid][offset]['name'] = sig._name
            offset += 1
```

Whether or not that'll actually work on the front end side I don't know and have no way of easily checking it now.

All that said, good luck! I miss the FS times. Drop me a message on twitter (@cdbrkfxrpt) if you like, I do a bunch of race car data analysis for money now but we're also doing [some small but cool electronics stuff with a good fit for FS and similar](https://bmc-board.com) and perhaps we can help you out in some way or other.

Cheers
Florian

**Comment by ekampourakis** [comment]
Thanks for your lightning fast reply!

Yes you guessed it right, I'm part of a formula student team. I wouldn't say we're relying on it but we're surely exploring our possibilities!

Your extended explanation covered my question even to the last detail. I will try to make it work and possibly extend it.

I will let you know about the result, as for now I'm closing this issues and I will reopen if more problems occur in the way.

Best regards,
Manos

**Comment by cdbrkfxrpt** [comment]
As I said, drop me a line via email or twitter if you are interested in some support, potentially on our hardware. This year would be difficult to realize something but we are looking for somebody to do a showcase with starting this September/October.
